# System modules prebuilt coming from Soong

# Extra inputs:
# LOCAL_SOONG_SYSTEM_MODULES_DIR
# LOCAL_SOONG_SYSTEM_MODULES_LIBS
# LOCAL_SOONG_SYSTEM_MODULES_DEPS

SOONG_SYSTEM_MODULES_$(LOCAL_MODULE) :=$= $(LOCAL_SOONG_SYSTEM_MODULES_DIR)
SOONG_SYSTEM_MODULES_LIBS_$(LOCAL_MODULE) :=$= $(LOCAL_SOONG_SYSTEM_MODULES_LIBS)
SOONG_SYSTEM_MODULES_DEPS_$(LOCAL_MODULE) :=$= $(LOCAL_SOONG_SYSTEM_MODULES_DEPS)

$(LOCAL_MODULE): $(SOONG_SYSTEM_MODULES_DEPS_$(LOCAL_MODULE))
.PHONY: $(LOCAL_MODULE)

LOCAL_SOONG_SYSTEM_MODULES_DIR :=
LOCAL_SOONG_SYSTEM_MODULES_LIBS :=
LOCAL_SOONG_SYSTEM_MODULES_DEPS :=
