# Target-specific configuration

ifeq ($(BOARD_USES_STE_HARDWARE),true)

    COMMON_GLOBAL_CFLAGS += -DSTE_HARDWARE
    COMMON_GLOBAL_CPPFLAGS += -DSTE_HARDWARE

    ifeq ($(BOARD_USES_STE_SAMSUNG_HARDWARE),true)
        COMMON_GLOBAL_CFLAGS += -DSTE_SAMSUNG_HARDWARE
        COMMON_GLOBAL_CPPFLAGS += -DSTE_SAMSUNG_HARDWARE
    endif

endif
