/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! `record-finalized-flags` is a tool to create a snapshot (intended to be stored in
//! prebuilts/sdk) of the flags used with @FlaggedApi APIs
use anyhow::Result;
use clap::Parser;
use std::{fs::File, path::PathBuf};

mod finalized_flags;
mod flag_report;

pub(crate) type FlagId = String;

const ABOUT: &str = "Create a new prebuilts/sdk/<version>/finalized-flags.txt file

The prebuilts/sdk/<version>/finalized-flags.txt files list all aconfig flags that have been used
with @FlaggedApi annotations on APIs that have been finalized. These files are used to prevent
flags from being re-used for new, unfinalized, APIs, and by the aconfig code generation.

This tool works as follows:

  - Read the previous finalized-flags.txt files from prebuilts/sdk [--finalized-flags-file]
  - Read the state of the currently flags in the source as generated by `metalava flag-report`, and
    filter out the flags marked as finalized [--flag-report]
  - Merge and sort the two inputs
  - Print the set of flags to stdout
";

#[derive(Parser, Debug)]
#[clap(about=ABOUT)]
struct Cli {
    #[arg(long)]
    finalized_flags: PathBuf,

    #[arg(long)]
    flag_report: PathBuf,
}

fn main() -> Result<()> {
    let args = Cli::parse();

    let file = File::open(args.finalized_flags)?;
    let already_finalized_flags = finalized_flags::read_finalized_flags(file)?;

    let file = File::open(args.flag_report)?;
    let newly_finalized_flags = flag_report::read_and_filter_flag_report(file)?;

    let mut all_finalized_flags: Vec<_> =
        already_finalized_flags.union(&newly_finalized_flags).map(|s| s.to_owned()).collect();
    all_finalized_flags.sort();

    println!("{}", all_finalized_flags.join("\n"));

    Ok(())
}
